project_name: kraken-dca
builds:
- env:
  - CGO_ENABLED=0
  binary: kraken-dca
  goos:
  - linux
  goarch:
  - amd64
  - arm64
dockers:
- image_templates:
  - "ghcr.io/primexz/kraken_dca:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/primexz/kraken_dca:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: "ghcr.io/primexz/kraken_dca:{{ .Version }}"
  image_templates:
  - "ghcr.io/primexz/kraken_dca:{{ .Version }}-amd64"
  - "ghcr.io/primexz/kraken_dca:{{ .Version }}-arm64v8"