project_name: kraken-dca
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
      - "7"
release:
  draft: true
snapshot:
  name_template: "{{ .Version }}-{{.ShortCommit}}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
dockers:
  - image_templates:
      - "ghcr.io/primexz/kraken_dca:{{ .Tag }}"
      - "ghcr.io/primexz/kraken_dca:latest"
changelog:
  use: github
  sort: asc